import { useEffect, useRef, useState } from 'react';
import { api, errorText, jsonBody } from './api';
import { TransactionTable } from './components';
import type { Category, Kind, Transaction } from './types';

export function TransactionsPage({ token }: { token: string }) {
  const [rows, setRows] = useState<Transaction[]>([]), [categories, setCategories] = useState<Category[]>([]), [error, setError] = useState(''), [busy, setBusy] = useState(false), [notice, setNotice] = useState('');
  const [kind, setKind] = useState<Kind>('INCOME'), [query, setQuery] = useState(''), [filter, setFilter] = useState(''), [start, setStart] = useState(''), [end, setEnd] = useState('');
  // The same payload keeps its key after an uncertain network failure.
  const pending = useRef<{ payload: string; key: string } | null>(null);
  const reload = async () => { const [t, c] = await Promise.all([api<Transaction[]>('/api/transactions', token), api<Category[]>('/api/categories', token)]); setRows(t.sort((a, b) => b.transactionAt.localeCompare(a.transactionAt) || b.transactionId - a.transactionId)); setCategories(c); };
  useEffect(() => { reload().catch(e => setError(errorText(e))); }, [token]);
  const visible = rows.filter(t => (!query || `${t.vendorName || ''} ${t.description || ''}`.toLowerCase().includes(query.toLowerCase())) && (!filter || t.categoryId === Number(filter)) && (!start || t.transactionAt.slice(0, 10) >= start) && (!end || t.transactionAt.slice(0, 10) <= end));
  return <><header><div><p className="eyebrow">TRANSACTIONS</p><h1>거래 내역</h1><p className="muted">잔액이 음수가 되지 않도록 수입을 먼저 등록해 주세요.</p></div></header><section className="card"><h2>새 거래 등록</h2><form className="transaction-form" onSubmit={async e => { e.preventDefault(); const form = e.currentTarget; const data = new FormData(form); const payload = { transactionType: kind, categoryId: Number(data.get('categoryId')), amount: Number(data.get('amount')), transactionAt: `${data.get('date')}T00:00:00`, vendorName: data.get('vendorName'), description: data.get('description') }; const serialized = JSON.stringify(payload); if (pending.current?.payload !== serialized) pending.current = { payload: serialized, key: crypto.randomUUID() }; setBusy(true); setError(''); setNotice(''); try { await api('/api/transactions', token, jsonBody({ ...payload, idempotencyKey: pending.current.key })); pending.current = null; form.reset(); setNotice('거래를 저장했습니다.'); await reload(); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }}>
    <label>구분<select value={kind} onChange={e => setKind(e.target.value as Kind)}><option value="INCOME">수입</option><option value="EXPENSE">지출</option></select></label><label>카테고리<select name="categoryId" key={kind} required>{categories.filter(c => c.type === kind).map(c => <option key={c.categoryId} value={c.categoryId}>{c.name}</option>)}</select></label><label>거래일<input name="date" type="date" max={localToday()} defaultValue={localToday()} required /></label><label>금액 (원)<input name="amount" type="number" min="0.01" step="0.01" max="9999999999999.99" required /></label><label>사용처<input name="vendorName" maxLength={255} placeholder="예: 동네 마트" /></label><label>설명<input name="description" maxLength={1000} placeholder="예: 주말 장보기" /></label><button className="primary" disabled={busy || !categories.length}>{busy ? '저장 중…' : '거래 저장'}</button>
  </form>{error && <p role="alert" className="error">{error}</p>}{notice && <p role="status" className="success">{notice}</p>}</section><section className="card"><h2>전체 거래 · {visible.length}건</h2><div className="filters"><label>검색<input placeholder="사용처 또는 설명" value={query} onChange={e => setQuery(e.target.value)} /></label><label>카테고리<select value={filter} onChange={e => setFilter(e.target.value)}><option value="">전체</option>{categories.map(c => <option key={c.categoryId} value={c.categoryId}>{c.name}</option>)}</select></label><label>시작일<input type="date" value={start} onChange={e => setStart(e.target.value)} /></label><label>종료일<input type="date" value={end} min={start} onChange={e => setEnd(e.target.value)} /></label></div><TransactionTable rows={visible} categories={categories} /><p className="muted small">최신 거래일 순입니다. 잔액 스냅샷을 보존하기 위해 수정·삭제는 제공하지 않습니다.</p></section></>;
}
function localToday() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; }
